# -*- coding: utf-8 -*-
"""Label dictionaries ported from BU/finya/profile.js (the `names` object).

Used to translate the numeric/string IDs found in a Finya profile JSON into
human-readable German labels.
"""

QNA = {
    "title": "100 Fragen",
    "subTitle": "Erzähle mehr über dich!",
    "noAnswer": "Noch keine Antwort",
    "groupProgress": "{{answers}} von {{questions}} beantwortet",
    "group_1": "Liebe und Partnerschaft",
    "group_2": "Lebensstil",
    "group_3": "Charakter",
    "group_4": "Äußerlichkeiten",
    "group_5": "Das Leben",
    "group_6": "Kultur",
    "group_7": "Reisen",
    "group_8": "Essen und Trinken",
    "group_9": "Beruf",
    "group_10": "Freunde, Familie, Heimat",
    "group_11": "Partnersuche online",
    "group_12": "Irrationales",
    "question_67": "Was hältst du von Treue?",
    "question_68": "Was ist für dich ein Trennungsgrund ohne Diskussion?",
    "question_69": "Glaubst du an Liebe auf den ersten Blick?",
    "question_70": "Glaubst du an Liebe auf den zweiten Blick?",
    "question_72": "Hattest du bereits richtig Glück in der Liebe?",
    "question_73": "Welche war deine schlimmste Abfuhr?",
    "question_74": "Wie gehst du mit einer Trennung um?",
    "question_29": "Wie sieht für dich ein ausgefülltes Liebesleben aus?",
    "question_34": "Was ist das »gewisse Etwas«, das er/sie haben muss?",
    "question_36": "Was lässt dich heute noch erröten?",
    "question_52": "Würdest du deinem Partner/deiner Partnerin etwas vorlesen?",
    "question_42": "Was tust du zu deiner Entspannung?",
    "question_76": "Wie ist dein Wohnstil?",
    "question_77": "Welchen Stellenwert nimmt Shopping für dich ein?",
    "question_78": "Wie sieht für dich ein perfektes Wochenende aus?",
    "question_79": "Was sind für dich gute Manieren?",
    "question_80": "Welche Trends findest du zurzeit spannend?",
    "question_37": "Interessierst du dich für Sport?",
    "question_38": "Treibst du aktiv Sport? Wenn ja, welche Sportart?",
    "question_82": "Wovon würdest du dich für kein Geld der Welt trennen?",
    "question_900": "Welche (technischen) Gimmicks magst du?",
    "question_71": "Bist du eifersüchtig?",
    "question_33": "Magst du spontane Begegnungen?",
    "question_15": "Bist du eitel?",
    "question_16": "Wie ist dein Verhältnis zu dir selbst?",
    "question_17": "Welche sind deine Schwächen?",
    "question_19": "Wie würdest du deine charakterlichen Vorzüge beschreiben?",
    "question_20": "Bist du tendenziell ehrlich?",
    "question_21": "Welche Grundwerte bestimmen dein Leben?",
    "question_25": "Was bedeutet für dich »emotionale Intelligenz«?",
    "question_4": "Wie wichtig ist für dich ein gepflegtes Äußeres?",
    "question_901": "Wann ist ein Mann für dich gepflegt?",
    "question_902": "Wann ist eine Frau für dich gepflegt?",
    "question_3": "Welche Äußerlichkeiten magst du nicht besonders bei Anderen?",
    "question_5": "Welche Düfte magst du?",
    "question_903": "Wie kleidest du dich?",
    "question_1": "Welche Veränderungen würdest du dir an deinem Körper wünschen?",
    "question_904": "Hast du besondere Pflegerituale?",
    "question_22": "Was hättest du in deinem Leben gerne anders oder auf keinen Fall anders gemacht?",
    "question_23": "Was hat dich zuletzt positiv überrascht?",
    "question_24": "Was ist der Sinn des Lebens?",
    "question_26": "Hast du noch Träume?",
    "question_27": "Welche deiner Träume werden nicht mehr in Erfüllung gehen können?",
    "question_66": "Was hältst du für die genialste Erfindung?",
    "question_14": "Wie wichtig ist Allgemeinbildung für dich?",
    "question_53": "Mit wem würdest du gerne eine Vernissage besuchen?",
    "question_54": "Magst du klassische Konzerte oder Opern?",
    "question_55": "Welches Theaterstück hat dich zuletzt begeistert?",
    "question_56": "Wann warst du das letzte Mal im Museum?",
    "question_57": "Hast du einen Lieblingsdichter?",
    "question_39": "Spielst du ein Musikinstrument?",
    "question_61": "Welche TV-Serien hast du als Kind gerne gesehen?",
    "question_905": "Welche Art von Filmen magst du?",
    "question_62": "Welche Musik/Bands magst du?",
    "question_41": "Wie wichtig ist Fernsehen für dich?",
    "question_906": "Wohin verreist du gerne?",
    "question_907": "Wie häufig verreist du privat?",
    "question_908": "Bist du geschäftlich viel auf Reisen?",
    "question_83": "Wie sieht dein Traumurlaub aus?",
    "question_909": "Welche Städte magst du gern?",
    "question_910": "Welche Reisen lässt du lieber Andere machen?",
    "question_911": "Pool oder Meer?",
    "question_912": "Business Class oder Anhalter?",
    "question_913": "Fünf Sterne oder Zelt?",
    "question_914": "Was ist für dich gutes Essen?",
    "question_915": "Was ist für dich schlechtes Essen?",
    "question_916": "In welche Art von Restaurants gehst du gerne essen?",
    "question_917": "Welche Art von Restaurants meidest du?",
    "question_75": "Hast du ein Lieblingsgericht? Wenn ja, welches?",
    "question_918": "Welche Speisen/Zutaten magst du nicht?",
    "question_919": "Was trinkst du gerne?",
    "question_920": "Kochst du gerne? Wenn ja, wie ist dein Kochstil?",
    "question_921": "Bevorzugst du bestimmte Länderküchen? Wenn ja, welche?",
    "question_10": "Hast du den Beruf, den du dir immer gewünscht hast?",
    "question_922": "Wie sieht dein beruflicher Alltag aus?",
    "question_11": "Wie sieht eine perfekte Berufssituation für dich aus?",
    "question_12": "Wie ist dein Verhältnis zu Geld?",
    "question_93": "Wie wichtig ist dir Familie?",
    "question_89": "Was bedeutet Weihnachten für dich?",
    "question_92": "Wie verbringst du idealerweise deinen Geburtstag?",
    "question_923": "Wie beschreibst du deinen Freundeskreis?",
    "question_924": "Wo ist für dich Zuhause?",
    "question_90": "Bist du heimatverbunden?",
    "question_91": "Welche Traditionen pflegst du?",
    "question_58": "Wie würden deine Schulfreunde dich heute beschreiben?",
    "question_43": "Hast du bereits jemanden über das Internet persönlich kennen gelernt?",
    "question_44": "Wie möchtest du in keinem Fall angesprochen/angemailt werden?",
    "question_45": "Was würdest du gerne hier bei Finya erleben?",
    "question_46": "Welche Erfahrungen hast du auf anderen Plattformen bereits gemacht?",
    "question_50": "Kommunizierst du lieber mit Nutzern, die ein Foto in ihrem Profil haben?",
    "question_51": "Wieviel Beachtung schenkst du einer möglichen Bedeutung eines Pseudonyms?",
    "question_925": "Wie nutzt du - neben Finya - noch das Internet?",
    "question_926": "Welche Websites besuchst du häufig?",
    "question_6": "Inwiefern glaubst du an Astrologie?",
    "question_7": "Welches ist dein Sternzeichen, und stimmen dessen Grundzüge mit dir überein?",
    "question_9": "Weißt du, welches Sternzeichen am besten zu dir passt?",
    "question_59": "Welche Aberglauben haben dich schon immer begleitet?",
    "question_60": "Was wirst du in zehn Jahren sein und machen?",
    "question_64": "In welchem Jahrhundert würdest du gerne leben?",
    "question_65": "Wie würde die Erde aussehen, wenn du sie erschaffen hättest?",
}

OPTIONS = {
    "mood1": "sehr gut",
    "mood2": "gut",
    "mood3": "zuversichtlich",
    "mood4": "verliebt",
    "mood5": "entspannt",
    "mood6": "müde",
    "mood7": "geht so",
    "mood8": "enttäuscht",
    "mood9": "einsam",
    "mood10": "krank",
    "month1": "Januar",
    "month2": "Februar",
    "month3": "März",
    "month4": "April",
    "month5": "Mai",
    "month6": "Juni",
    "month7": "Juli",
    "month8": "August",
    "month9": "September",
    "month10": "Oktober",
    "month11": "November",
    "month12": "Dezember",
    "feelsLike1": "ein Dinner für zwei",
    "feelsLike2": "Kochen zu zweit",
    "feelsLike3": "Tanzen",
    "feelsLike4": "Kino allein",
    "feelsLike5": "Kino zu zweit",
    "feelsLike6": "TV-Abend allein",
    "feelsLike7": "TV-Abend zu zweit",
    "feelsLike8": "Ein paar Drinks",
    "feelsLike9": "eine Reise",
    "feelsLike10": "Küssen",
    "feelsLike11": "Theater",
    "feelsLike12": "ein Konzert",
    "feelsLike13": "...Sag du's mir!",
    "feelsLike14": "eine Party",
    "feelsLike21": "die nächste Staffel",
    "feelsLike22": "ein gutes Buch",
    "feelsLike23": "einen guten Wein",
    "feelsLike24": "einen Videochat",
    "feelsLike25": "Home-Workout",
    "feelsLike26": "Frühjahrsputz",
    "feelsLike27": "neue Rezeptideen",
    "feelsLike28": "humorvolle Ablenkung",
    "feelsLike29": "positiven Austausch",
    "feelsLike30": "frische Luft",
    "educationLanguage_DE": "Deutsch",
    "educationLanguage_SQ": "Albanisch",
    "educationLanguage_AR": "Arabisch",
    "educationLanguage_BG": "Bulgarisch",
    "educationLanguage_ZH": "Chinesisch",
    "educationLanguage_DA": "Dänisch",
    "educationLanguage_EN": "Englisch",
    "educationLanguage_ET": "Estnisch",
    "educationLanguage_XY": "Fachchinesisch",
    "educationLanguage_FI": "Finnisch",
    "educationLanguage_FR": "Französisch",
    "educationLanguage_EL": "Griechisch",
    "educationLanguage_HI": "Hindi",
    "educationLanguage_IT": "Italienisch",
    "educationLanguage_GA": "Irisch",
    "educationLanguage_JW": "Japanisch",
    "educationLanguage_KO": "Koreanisch",
    "educationLanguage_HR": "Kroatisch",
    "educationLanguage_KU": "Kurdisch",
    "educationLanguage_LA": "Latein",
    "educationLanguage_LV": "Lettisch",
    "educationLanguage_LT": "Litauisch",
    "educationLanguage_MT": "Maltesisch",
    "educationLanguage_NL": "Niederländisch",
    "educationLanguage_NO": "Norwegisch",
    "educationLanguage_PL": "Polnisch",
    "educationLanguage_PT": "Portugiesisch",
    "educationLanguage_RO": "Rumänisch",
    "educationLanguage_RU": "Russisch",
    "educationLanguage_SV": "Schwedisch",
    "educationLanguage_SR": "Serbisch",
    "educationLanguage_SK": "Slowakisch",
    "educationLanguage_SL": "Slowenisch",
    "educationLanguage_ES": "Spanisch",
    "educationLanguage_TH": "Thai",
    "educationLanguage_CS": "Tschechisch",
    "educationLanguage_TR": "Türkisch",
    "educationLanguage_UK": "Ukrainisch",
    "educationLanguage_HU": "Ungarisch",
    "educationLanguage_VI": "Vietnamesisch",
    "educationLanguage_XX": "andere",
    "bodyShape1": "Schlank",
    "bodyShape2": "Athletisch",
    "bodyShape3": "Normale Figur",
    "bodyShape4": "Ein paar Kilo mehr",
    "bodyShape5": "Beachtliche Figur",
    "eyeColor1": "Bernsteinfarbene Augen",
    "eyeColor2": "Blaue Augen",
    "eyeColor3": "Braune Augen",
    "eyeColor4": "Graue Augen",
    "eyeColor5": "Haselnussbraune Augen",
    "eyeColor6": "Grüne Augen",
    "eyeColor7": "Graublaue Augen",
    "eyeColor8": "Graugrüne Augen",
    "eyeColor9": "»Andere« Augenfarbe",
    "eyeColor10": "Grünbraune Augen",
    "relationshipStatus1": "Single",
    "relationshipStatus5": "Getrennt lebend",
    "relationshipStatus6": "Geschieden",
    "relationshipStatus7": "Verwitwet",
    "relationshipStatus8": "Es ist kompliziert",
    "relationshipStatus9": "Gespannt auf Neues",
    "school1": "Realschule",
    "school2": "Hauptschule",
    "school3": "Gymnasium",
    "school4": "Berufsschule",
    "school5": "Fachhochschule",
    "school6": "Universität (Inland)",
    "school7": "Universität (Ausland)",
    "school11": "GCSE",
    "school12": "A-Levels",
    "school13": "IB",
    "school14": "University",
    "school15": "University (abroad)",
    "hairColor1": "Platinblond",
    "hairColor2": "Blond",
    "hairColor3": "Dunkelblond",
    "hairColor4": "Rotblond",
    "hairColor5": "Rote Haare",
    "hairColor6": "Brünett",
    "hairColor7": "Braune Haare",
    "hairColor8": "Dunkelbraune Haare",
    "hairColor9": "Schwarze Haare",
    "hairColor10": "Graue Haare",
    "hairColor11": "»Andere« Haarfarbe",
    "hairStyle1": "Kurze Haare",
    "hairStyle1_alternative": "Kurz",
    "hairStyle2": "Kurz, lockig",
    "hairStyle3": "Kinnlange Haare",
    "hairStyle3_alternative": "Kinnlang",
    "hairStyle4": "Kinnlang, lockig",
    "hairStyle5": "Lange Haare",
    "hairStyle5_alternative": "Lang",
    "hairStyle6": "Lange, lockig",
    "hairStyle7": "Bob",
    "hairStyle8": "Pony",
    "hairStyle9": "Pferdeschwanz",
    "hairStyle10": "»Andere« Frisur",
    "hairStyle11": "Glatze",
    "children_yes": "ja",
    "children_none": "keine",
    "childrenPlan_yes": "ja",
    "childrenPlan_none": "eher nein",
    "moving_yes": "vorhanden",
    "smoking_yes": "ja",
    "smoking_no": "nein",
    "photo_vote_1": "mind. 5,0",
    "photo_vote_2": "mind. 5,5",
    "photo_vote_3": "mind. 6,0",
    "photo_vote_4": "mind. 6,5",
    "photo_vote_5": "mind. 7,0",
    "photo_vote_6": "mind. 7,5",
    "photo_vote_7": "mind. 8,0",
    "photo_vote_8": "mind. 8,5",
    "photo_vote_9": "mind. 9,0",
    "signs1": "Steinbock",
    "signs2": "Wassermann",
    "signs3": "Fische",
    "signs4": "Widder",
    "signs5": "Stier",
    "signs6": "Zwillinge",
    "signs7": "Krebs",
    "signs8": "Löwe",
    "signs9": "Jungfrau",
    "signs10": "Waage",
    "signs11": "Skorpion",
    "signs12": "Schütze",
    "lookingFor1": "Feste Partnerschaft",
    "lookingFor2": "Netten Flirt",
    "lookingFor4": "Eine Freundschaft",
    "lookingFor5": "Gemeinsam reisen",
    "lookingFor6": "Gemeinsam ausgehen",
    "lookingFor7": "Kulturelle Aktivitäten",
    "lookingFor8": "Nette Bekanntschaft",
    "jobs1": "Agrarwirtschaft",
    "jobs2": "Alternative Medizin",
    "jobs3": "Andere",
    "jobs4": "Anlagen & Einrichtungen",
    "jobs5": "Architektur & Bauwesen",
    "jobs6": "Arzneimittel",
    "jobs7": "Automobilindustrie",
    "jobs8": "Bankwesen",
    "jobs9": "Baugewerbe",
    "jobs10": "Bauingenieurwesen",
    "jobs11": "Baustoffe",
    "jobs12": "Beratung/Consulting",
    "jobs13": "Bergbau & Metalle",
    "jobs14": "Bibliotheken",
    "jobs15": "Bildungswesen",
    "jobs16": "Biotechnologie",
    "jobs17": "Bürgerinitiativen & soziale Einrichtungen",
    "jobs18": "Chemieindustrie",
    "jobs19": "Coaching",
    "jobs20": "Computer & Netzwerksicherheit",
    "jobs21": "Computer Hardware",
    "jobs22": "Computer Networking",
    "jobs23": "Computer Software",
    "jobs24": "Computerspiele",
    "jobs25": "Design",
    "jobs26": "Dienstleistungen",
    "jobs27": "Druck",
    "jobs28": "E-Learning",
    "jobs29": "Einzelhandel",
    "jobs30": "Eisenbahn",
    "jobs31": "Elektrotechnik",
    "jobs32": "Energiewirtschaft",
    "jobs33": "Erneuerbare Energiequellen & Umwelt",
    "jobs34": "Facility Management",
    "jobs35": "Film",
    "jobs36": "Finanzdienstleistungen",
    "jobs37": "Fischerei",
    "jobs38": "Fluggesellschaften",
    "jobs39": "Forschung",
    "jobs40": "Fotografie",
    "jobs41": "Freizeit & Tourismus",
    "jobs42": "Freizeiteinrichtungen & -dienstleistungen",
    "jobs43": "Garten- und Landschaftsbau",
    "jobs44": "Gemeinnützige Einrichtungen",
    "jobs45": "Geologie",
    "jobs46": "Geschäftszubehör & -ausstattung",
    "jobs47": "Gesundheit & Fitness",
    "jobs48": "Glas & Keramik",
    "jobs49": "Grafikdesign",
    "jobs50": "Großhandel",
    "jobs51": "Halbleiter",
    "jobs52": "Hochschulen",
    "jobs53": "Holzwerkstoffindustrie",
    "jobs54": "Hotel & Gaststätten",
    "jobs55": "Immobilien",
    "jobs56": "Import & Export",
    "jobs57": "Industrielle Automatisierungstechnik",
    "jobs58": "Informationsdienste",
    "jobs59": "Informationstechnologie & -dienste",
    "jobs60": "Internationale Angelegenheiten",
    "jobs61": "Internationaler Handel & Entwicklung",
    "jobs62": "Internet",
    "jobs63": "Investment Banking",
    "jobs64": "Journalismus",
    "jobs65": "Kinderbetreuung",
    "jobs66": "Konsumgüter",
    "jobs67": "Kosmetik",
    "jobs68": "Kunst- & Kunsthandwerk",
    "jobs69": "Kunststofftechnik",
    "jobs70": "Lebensmittel",
    "jobs71": "Logistik & Zulieferung",
    "jobs72": "Luft- und Raumfahrt",
    "jobs73": "Luxusgüter & Schmuck",
    "jobs74": "Marketing & Werbung",
    "jobs75": "Marktforschung",
    "jobs76": "Maschinenanlagen",
    "jobs77": "Maschinenbau & Betriebstechnik",
    "jobs78": "Medienproduktion",
    "jobs79": "Medizinische Dienste",
    "jobs80": "Medizinische Geräte",
    "jobs81": "Messtechnik/Regeltechnik",
    "jobs82": "Metallindustrie / -verarbeitung",
    "jobs83": "Mode/Bekleidungsindustrie",
    "jobs84": "Museen & Kultureinrichtungen",
    "jobs85": "Musik",
    "jobs86": "Möbel",
    "jobs87": "Nanotechnologie",
    "jobs88": "Öffentlicher Dienst",
    "jobs89": "Öffentlichkeitsarbeit & Kommunikation",
    "jobs90": "Öl & Energie",
    "jobs91": "Onlinemedien",
    "jobs92": "Outsourcing/Offshoring",
    "jobs93": "Papier- & Forstprodukte",
    "jobs94": "Personalbeschaffung",
    "jobs95": "Personalwesen",
    "jobs96": "Pflegeberufe",
    "jobs97": "Pharmazeutische Industrie",
    "jobs98": "Politik",
    "jobs99": "Printmedien",
    "jobs100": "Prozessmanagement",
    "jobs101": "Psychologie/Psychotherapie",
    "jobs102": "Rechnungswesen",
    "jobs103": "Rechtsberatung",
    "jobs104": "Recycling & Entsorgung",
    "jobs105": "Restaurants & Gastronomie",
    "jobs106": "Rundfunk & Fernsehen",
    "jobs107": "Schiffbau",
    "jobs108": "Schreiben & Lektorat",
    "jobs109": "Seefahrt",
    "jobs110": "Sicherheit & Ermittlungen",
    "jobs111": "Sozial- und Gesundheitswesen",
    "jobs112": "Spendenaktionen",
    "jobs113": "Sport",
    "jobs114": "Steuerberatung/Wirtschaftsprüfung",
    "jobs115": "Telekommunikation",
    "jobs116": "Textilindustrie",
    "jobs117": "Theater/Bühne/Kino",
    "jobs118": "Tiermedizin",
    "jobs119": "Übersetzung & Lokalisierung",
    "jobs120": "Umweltdienste",
    "jobs121": "Unterhaltungsbranche",
    "jobs122": "Unterhaltungselektronik",
    "jobs123": "Unternehmensberatung",
    "jobs124": "Venture Capital & Private Equity",
    "jobs125": "Veranstaltungsdienstleistungen",
    "jobs126": "Verbundwerkstoffindustrie",
    "jobs127": "Verkehrstechnik",
    "jobs128": "Verlagswesen",
    "jobs129": "Versand & Container",
    "jobs130": "Versicherungen",
    "jobs131": "Verteidigungsindustrie/Militär",
    "jobs132": "Wein- & Spirituosenhandel",
}

HABITS = {
    "eatingHabits": {
        1: "🥬 Vegetarisch",
        2: "🥬 Vegan",
        3: "🍽️ Kulinarisch aufgeschlossen",
        4: "🍽️ Gutes Essen",
        5: "🍎 Bioladen",
        6: "🥕 Biokiste",
        7: "🛒 Discounter",
        8: "🧺 Wochenmarkt",
        9: "🥡 Lieferservice",
        10: "🌟 Sterneküche",
        11: "🍽️ Essen gehen",
        12: "👩‍🍳 Kochen",
        13: "🍽️ Schnelles Essen",
        14: "🍽️ Günstiges Essen",
        15: "🥐 Französische Küche",
        16: "🍝 Italienische Küche",
        17: "🥢 Asiatische Küche",
        18: "🫒 Spanische Küche",
        19: "🍣 Sushi",
    },
    "mobilityHabits": {
        1: "🚗 Auto",
        2: "🔌 E-Auto",
        3: "🚲 E-Bike",
        4: "🛴 E-Scooter",
        5: "🚲 Fahrrad",
        6: "🚅 Fernbahn",
        7: "✈️ Flugzeug",
        8: "🚲 Liegerad",
        9: "🛳️ Kreuzfahrtschiff",
        10: "🛵 Mofa/Moped",
        11: "🏍️ Motorrad",
        12: "🛥️ Motorboot",
        13: "🚇 Öffis",
        14: "🚌 Reisebus",
        15: "⛵ Segelboot",
        16: "🛹 Skateboard",
        17: "🚶 Zu Fuß",
    },
    "tvHabits": {
        1: "📺 Actionfilme",
        2: "📺 Anime",
        3: "📺 Arthouse",
        4: "📺 Blockbuster",
        5: "📺 Comedy",
        6: "📺 Dokus",
        7: "📺 Dramen",
        8: "📰 Fernsehzeitschrift",
        9: "📺 Filme",
        10: "😱 Horrorfilme",
        11: "📺 Independent-Filme",
        12: "📺 Internationale Filme",
        13: "📺 Kinder- und Familienfilme",
        14: "📺 Kultur",
        15: "❤️‍🔥 Liebesfilme",
        16: "📺 Lineares Fernsehen",
        17: "📺 Mediatheken",
        18: "📺 Musik, Konzerte",
        19: "📺 Nachrichten",
        20: "📺 Streaming",
        21: "📺 Öffentlich Rechtliche",
        22: "📺 Privatsender",
        23: "📺 Reality TV",
        24: "👾 Science Fiction & Fantasy",
        25: "📺 Serien",
        26: "📺 Sport",
        27: "📺 Thriller",
    },
    "musicHabits": {
        1: "🎵 Alternative",
        2: "💿 CDs",
        3: "🎵 Chansons",
        4: "🎵 Charts",
        5: "🎵 Country",
        6: "🎵 Dance",
        7: "🎵 Electronic",
        8: "🎵 Folk",
        9: "🎵 Hi-Fi",
        10: "🎵 Hip-Hop/Rap",
        11: "🎵 House",
        12: "🎷 Jazz",
        13: "🎹 Klassische Musik",
        14: "🎵 Latin",
        15: "🎵 Vinyl",
        16: "🎵 Pop",
        17: "🎵 Punk",
        18: "🎵 R&B/Soul",
        19: "🎸 Rock",
        20: "🎵 Schlager",
        21: "🎵 Singer/Songwriter",
        22: "🎵 Soundtracks",
        23: "🎵 Streaming",
        24: "🎵 Weltmusik",
    },
}
